#!/usr/bin/env bash
# install nginx and adjust default homepage
# add redirection
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echoSchool > /var/www/html/index.nginx-debian.html
sed -i "/^\sserver_name.*/a\	rewrite ^/redirect_me https://www.youtube.com/@foglight4370  permanent;" /etc/nginx/sites-available/default;
service nginx start
