#!/usr/bin/env bash
# A Bash script that loops from 1 to 10 and displays different messages depending on the loop iteration
counter=1
while [ $counter -lt 11 ]
do
  if [ $counter -eq 4 ]
  then
    echo bad luck
  elif [ $counter -eq 8 ]
  then
    echo good luck
 else
   echo Best School
fi
counter=$((counter + 1))
done
