#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and displays different messages for some of them
counter=1

while [ $counter -lt 21 ]
do
  echo $counter

  case $counter in
    4)
      echo bad luck from China
      ;;
    9)
      echo bad luck from Japan
      ;;
    17)
      echo bad luck from Italy
      ;;
    *)
      ;;
  esac

  counter=$((counter + 1))
done
