#!/usr/bin/env bash
# A Bash script that displays the content of the current directory in a list format, where only the part of the name after the first dash is displayed
list=$(ls -1)
for f in $list; do
	echo "$f" | cut -d "-" -f2-
done
